### PR TITLE
Generate additional dark themes

### PR DESCRIPTION
**Pull request by ajorgensen**
I hacked together a script to generate these templates programmatically. I'll need to do some manual QA and I am quite sure that my methodology here could be improved but I hacked this taken in an hour or so, hopefully its helpful.

The end result looks pretty close to my eye, however a more keen observer will likely find some discrepancies between the canonical theme and these generated ones. 

To further improve this, I could use the same methodology to generate an real template that is able to take the values from lua and map them directly into the vscode theme (without using the gsub hack). This would also highlight places where colors may not match 1:1 between the nvim theme an vscode theme which the gsub method I used would miss entirely.

# Methodology
Basically I took all of the colors that are defined for each of the themes from https://github.com/EdenEast/nightfox.nvim/tree/main/lua/nightfox/precompiled/nvim and using `nightfox-dark-theme.json` I was able to take all of the colors defined in `nightfox_compiled.lua` and substitute them for colors in other themes. This approach gave me a new `*-dark-theme.json` that could be used in vscode. It looks like there were a few colors missed for the light theme, most notably the search bar background was still dark, so I'll need to go over those more carefully. 

This was the ruby script I hacked together to do the substitution, this was a quick hackjob so there's probably a better way to automate this but I'll post it here for posterity for those interested.

```ruby
template_theme = { :name => "nightfox", :type => "dark" }

themes = [
  { :name => "dawnfox", :type => "light" },
  { :name => "dayfox", :type => "light" },
  { :name => "duskfox", :type => "dark" },
  { :name => "nightfox", :type => "dark" },
  { :name => "nordfox", :type => "dark" },
  { :name => "terafox", :type => "dark" },
  { :name => "carbonfox", :type => "dark" },
]

def compiled_theme_filename(theme)
  "#{theme[:name]}_compiled.lua"
end

def extract_colors(theme)
  filename = compiled_theme_filename(theme)
  data = File.read(filename)
  return data.scan(/"(#.*?)"/).flatten
end

def template_filename(theme)
  "#{theme[:name]}-#{theme[:type]}-theme.json"
end

themes.each do |theme|
  template_colors = extract_colors(template_theme)
  theme_colors = extract_colors(theme)

  from_filename = template_filename(template_theme)
  to_filename = template_filename(theme)

  data = File.read(from_filename)

  template_colors.each_with_index do |from_color, idx|
    to_color = theme_colors[idx]

    data = data.gsub(from_color, to_color)
  end

  File.open("./themes/#{to_filename}", 'w') { |file| file.write(data) }
end
```

### CODE REVIEW

**Comment by f1yn** [comment]
@keifererikson any update on this?

**Comment by treturner** [comment]
I've been dying to have terrafox ported over because I recently switched off of nvim and that was my favorite theme.

**Comment by Fr4nk1inCs** [comment]
Any update?

**Comment by z3ugma** [comment]
@keifererikson would you merge this PR? I'm keen to have all the *fox themes available for VS Code

**Comment by z3ugma** [comment]
🔥 🔥

**Comment by f1yn** [comment]
My favorite theme is back from the dead 🥺

**Pull request merged**
